baseURL = 'https://joelsleeba.github.io/blog'
languageCode = 'en-us'
title = "Sleeba's Shell Scripts"
theme = ["cactus", "hugo-shortcode-gallery"]
publishdir = 'public'
copyright = "Joel Sleeba"

# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "Gallery"
url = "/gallery"
weight = 4

[[menu.main]]
name = "About"
url = "https://joelsleeba.github.io"
weight = 5


[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "pygments"
    tabWidth = 4
    
[params]
    description = "I'm Joel Sleeba. I am a 2nd year graduate student at [IISER Thiruvananthapuram](https://iisertvm.ac.in). I am interested in Fourier analysis and related areas and currently doing my major project under the supervision of [Dr. P Devaraj](https://iisertvm.ac.in/faculty/devarajp). Apart from math, I'm interested in computer programming, linux, photography and movies. You can find some of my projects in my GitHub repositories"
    colortheme = "white"
    mainSectionTitle = "Blog"
    showAllPostsOnHomePage = false
    postsOnHomePage = 5
    tagsOverview = true
    tocInline = false
    
    mathjax = true
    katex = true
    loadJQuery = false
    dateFormat = "02 January, 2006"
    
[[params.social]]
  name = "github"
  link = "https://github.com/joelsleeba"

[[params.social]]
  name = "email"
  link = "joelsleeba24@gmail.com"
